import address from '@noaejs/deps/compiled/address';
import * as parser from '@noaejs/deps/compiled/babel/parser';
import * as traverse from '@noaejs/deps/compiled/babel/traverse';
import * as t from '@noaejs/deps/compiled/babel/types';
import chalk from '@noaejs/deps/compiled/chalk';
import spawn from '@noaejs/deps/compiled/cross-spawn';
import createDebug, { Debugger } from '@noaejs/deps/compiled/debug';
import deepmerge from '@noaejs/deps/compiled/deepmerge';
import execa from '@noaejs/deps/compiled/execa';
import glob from '@noaejs/deps/compiled/glob';
import got from '@noaejs/deps/compiled/got';
import lodash from '@noaejs/deps/compiled/lodash';
import mkdirp from '@noaejs/deps/compiled/mkdirp';
import Mustache from '@noaejs/deps/compiled/mustache';
import pkgUp from '@noaejs/deps/compiled/pkg-up';
import portfinder from '@noaejs/deps/compiled/portfinder';
import prompts from '@noaejs/deps/compiled/prompts';
import resolve from '@noaejs/deps/compiled/resolve';
import rimraf from '@noaejs/deps/compiled/rimraf';
import semver from '@noaejs/deps/compiled/semver';
import signale from '@noaejs/deps/compiled/signale';
import yargs from '@noaejs/deps/compiled/yargs';
import yParser from '@noaejs/deps/compiled/yargs-parser';
// TODO: uncomment
// import * as chokidar from '@umijs/deps/reexported/chokidar';
// import clipboardy from '@umijs/deps/reexported/clipboardy';

export { default as BabelRegister } from './BabelRegister/BabelRegister';
export { default as cheerio } from './cheerio/cheerio';
export { default as cleanRequireCache } from './cleanRequireCache/cleanRequireCache';
export { default as compatESModuleRequire } from './compatESModuleRequire/compatESModuleRequire';
export { default as delay } from './delay/delay';
export { default as Generator } from './Generator/Generator';
export { default as getFile } from './getFile/getFile';
export { default as isLernaPackage } from './isLernaPackage/isLernaPackage';
export { default as mergeConfig } from './mergeConfig/mergeConfig';
export { default as parseRequireDeps } from './parseRequireDeps/parseRequireDeps';
export { default as randomColor } from './randomColor/randomColor';
export * from './routes';
export * from './ssr';
export * from './types';
export { default as winEOL, isWindows } from './winEOL/winEOL';
export { default as winPath } from './winPath/winPath';
export { spawn };
export { semver };
export { address };
export { chalk };
// export { clipboardy };
// export { chokidar };
export { createDebug, Debugger };
export { deepmerge };
export { execa };
export { lodash };
export { glob };
export { got };
export { prompts };
export { portfinder };
export { pkgUp };
export { resolve };
export { yargs };
export { mkdirp };
export { Mustache };
export { rimraf };
export { yParser };
export { t };
export { parser };
export { traverse };
export { signale };
